#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CustomExtensions;
    using LachlanBarclayNet.DAO;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Layout.cshtml")]
    public partial class _Views_Shared__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Layout_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html");

WriteLiteral(" lang=\"en\"");

WriteLiteral(">\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width\"");

WriteLiteral(" />\r\n    <title>");

            
            #line 6 "..\..\Views\Shared\_Layout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <meta");

WriteLiteral(" property=\'og:title\'");

WriteAttribute("content", Tuple.Create(" content=\'", 196), Tuple.Create("\'", 220)
            
            #line 7 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 206), Tuple.Create<System.Object, System.Int32>(ViewBag.Title
            
            #line default
            #line hidden
, 206), false)
);

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" property=\'og:description\'");

WriteAttribute("content", Tuple.Create(" content=\'", 261), Tuple.Create("\'", 291)
            
            #line 8 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 271), Tuple.Create<System.Object, System.Int32>(ViewBag.Description
            
            #line default
            #line hidden
, 271), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("    ");

            
            #line 9 "..\..\Views\Shared\_Layout.cshtml"
Write(Styles.Render("~/Content/css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <link");

WriteLiteral(" rel=\"shortcut icon\"");

WriteLiteral(" href=\"/favicon.ico\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"icon\"");

WriteLiteral(" href=\"/favicon.ico\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(">\r\n    <link");

WriteLiteral(" href=\'https://fonts.googleapis.com/css?family=Open+Sans:400,300,600\'");

WriteLiteral(" rel=\'stylesheet\'");

WriteLiteral(" type=\'text/css\'");

WriteLiteral(">\r\n</head>\r\n<body>\r\n    <div");

WriteLiteral(" class=\"blog-masthead\"");

WriteLiteral(">\r\n        \r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            <h1");

WriteLiteral(" class=\"blog-title\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 713), Tuple.Create("\"", 722)
, Tuple.Create(Tuple.Create("", 720), Tuple.Create<System.Object, System.Int32>(Href("~/")
, 720), false)
);

WriteLiteral(">Lachlan (Rocklan) Barclay\'s Blog</a></h1>\r\n            <nav");

WriteLiteral(" class=\"blog-nav\"");

WriteLiteral(" style=\"float: right;\"");

WriteLiteral(">\r\n                <a");

WriteAttribute("class", Tuple.Create(" class=\"", 843), Tuple.Create("\"", 890)
, Tuple.Create(Tuple.Create("", 851), Tuple.Create("btn", 851), true)
, Tuple.Create(Tuple.Create(" ", 854), Tuple.Create("btn-primary", 855), true)
            
            #line 20 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create(" ", 866), Tuple.Create<System.Object, System.Int32>(ViewBag.MenuItemClass1
            
            #line default
            #line hidden
, 867), false)
);

WriteAttribute("href", Tuple.Create(" href=\"", 891), Tuple.Create("\"", 900)
, Tuple.Create(Tuple.Create("", 898), Tuple.Create<System.Object, System.Int32>(Href("~/")
, 898), false)
);

WriteLiteral(">Home</a>\r\n                <a");

WriteAttribute("class", Tuple.Create(" class=\"", 930), Tuple.Create("\"", 977)
, Tuple.Create(Tuple.Create("", 938), Tuple.Create("btn", 938), true)
, Tuple.Create(Tuple.Create(" ", 941), Tuple.Create("btn-primary", 942), true)
            
            #line 21 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create(" ", 953), Tuple.Create<System.Object, System.Int32>(ViewBag.MenuItemClass2
            
            #line default
            #line hidden
, 954), false)
);

WriteAttribute("href", Tuple.Create(" href=\"", 978), Tuple.Create("\"", 1012)
, Tuple.Create(Tuple.Create("", 985), Tuple.Create<System.Object, System.Int32>(Href("~/search?category=technical")
, 985), false)
);

WriteLiteral(">Tech</a>\r\n                <a");

WriteAttribute("class", Tuple.Create(" class=\"", 1042), Tuple.Create("\"", 1089)
, Tuple.Create(Tuple.Create("", 1050), Tuple.Create("btn", 1050), true)
, Tuple.Create(Tuple.Create(" ", 1053), Tuple.Create("btn-primary", 1054), true)
            
            #line 22 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create(" ", 1065), Tuple.Create<System.Object, System.Int32>(ViewBag.MenuItemClass3
            
            #line default
            #line hidden
, 1066), false)
);

WriteAttribute("href", Tuple.Create(" href=\"", 1090), Tuple.Create("\"", 1120)
, Tuple.Create(Tuple.Create("", 1097), Tuple.Create<System.Object, System.Int32>(Href("~/search?category=music")
, 1097), false)
);

WriteLiteral(">Music</a>\r\n                <a");

WriteAttribute("class", Tuple.Create(" class=\"", 1151), Tuple.Create("\"", 1198)
, Tuple.Create(Tuple.Create("", 1159), Tuple.Create("btn", 1159), true)
, Tuple.Create(Tuple.Create(" ", 1162), Tuple.Create("btn-primary", 1163), true)
            
            #line 23 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create(" ", 1174), Tuple.Create<System.Object, System.Int32>(ViewBag.MenuItemClass4
            
            #line default
            #line hidden
, 1175), false)
);

WriteAttribute("href", Tuple.Create(" href=\"", 1199), Tuple.Create("\"", 1215)
, Tuple.Create(Tuple.Create("", 1206), Tuple.Create<System.Object, System.Int32>(Href("~/contact")
, 1206), false)
);

WriteLiteral(">Contact</a>\r\n            </nav>\r\n        </div>\r\n    </div>\r\n    <br />\r\n    <di" +
"v");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-sm-8 blog-main\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 32 "..\..\Views\Shared\_Layout.cshtml"
           Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("   \r\n            </div>\r\n\r\n            <div");

WriteLiteral(" class=\"col-sm-3 col-sm-offset-1 blog-sidebar\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"sidebar-module sidebar-module-inset\"");

WriteLiteral(" id=\"Sidebar1\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" src=\"/pics/headshot.jpg\"");

WriteLiteral(" class=\"img-responsive headshot\"");

WriteLiteral(" alt=\'lachlan barclay\'");

WriteLiteral(" />\r\n                    <p>Hi, I\'m Lachlan B, aka <a");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" href=\"https://twitter.com/rocklan\"");

WriteLiteral(">rocklan</a>. I\'m the rockstar developer.</p>\r\n                    <ol");

WriteLiteral(" class=\"list-unstyled\"");

WriteLiteral(">\r\n                        <li><a");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" href=\"https://twitter.com/rocklan\"");

WriteLiteral(">my twitter</a></li>\r\n                        <li><a");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" href=\"https://youtube.com/VoiceOfApollo\"");

WriteLiteral(">my videos</a></li>\r\n                        <li><a");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" href=\"https://lachlanbarclay.bandcamp.com\"");

WriteLiteral(">my music</a></li>\r\n                    </ol>\r\n                </div>\r\n\r\n        " +
"        <div");

WriteLiteral(" class=\"sidebar-module sidebar-module-inset\"");

WriteLiteral(" id=\"Sidebar5\"");

WriteLiteral(">\r\n                    <h4>Popular articles</h4>\r\n                    <ol");

WriteLiteral(" class=\"list-unstyled\"");

WriteLiteral(" id=\"populararticles\"");

WriteLiteral(">\r\n                        <li> <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2499), Tuple.Create("\"", 2555)
, Tuple.Create(Tuple.Create("", 2506), Tuple.Create<System.Object, System.Int32>(Href("~/2016/08/automated-build-with-gitlab-and-jenkins")
, 2506), false)
);

WriteLiteral(">Automated build with Gitlab and Jenkins</a></li>\r\n                        <li> <" +
"a");

WriteAttribute("href", Tuple.Create(" href=\"", 2638), Tuple.Create("\"", 2712)
, Tuple.Create(Tuple.Create("", 2645), Tuple.Create<System.Object, System.Int32>(Href("~/2016/02/asp-dot-net-two-factor-auth-with-google-authenticator-app")
, 2645), false)
);

WriteLiteral(">Two Factor Auth with Google\'s Authenticator App in  ASP.NET </a></li>\r\n         " +
"               <li> <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2816), Tuple.Create("\"", 2874)
, Tuple.Create(Tuple.Create("", 2823), Tuple.Create<System.Object, System.Int32>(Href("~/2015/08/how-to-be-the-best-developer-in-the-world")
, 2823), false)
);

WriteLiteral(">How to be the best developer in the world</a></li>\r\n                        <li>" +
" <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2959), Tuple.Create("\"", 3004)
, Tuple.Create(Tuple.Create("", 2966), Tuple.Create<System.Object, System.Int32>(Href("~/2011/01/friendly-urls-in-classic-asp")
, 2966), false)
);

WriteLiteral(">Friendly URLs in classic ASP</a></li>\r\n                        <li> <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3076), Tuple.Create("\"", 3128)
, Tuple.Create(Tuple.Create("", 3083), Tuple.Create<System.Object, System.Int32>(Href("~/2017/05/electron-app-vs-native-winforms-app")
, 3083), false)
);

WriteLiteral(">Electron app vs native winforms app</a></li>\r\n                        <li> <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3207), Tuple.Create("\"", 3255)
, Tuple.Create(Tuple.Create("", 3214), Tuple.Create<System.Object, System.Int32>(Href("~/2015/03/moving-from-classic-asp-to-mvc5")
, 3214), false)
);

WriteLiteral(">Moving from classic asp to mvc5</a></li>\r\n                        <li> <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3330), Tuple.Create("\"", 3393)
, Tuple.Create(Tuple.Create("", 3337), Tuple.Create<System.Object, System.Int32>(Href("~/2015/03/generating-barcodes-with-zen-barcode-generator")
, 3337), false)
);

WriteLiteral(">Generating barcodes with zen barcode generator</a></li>\r\n                    </o" +
"l>\r\n                </div>\r\n\r\n\r\n                <div");

WriteLiteral(" class=\"sidebar-module sidebar-module-inset\"");

WriteLiteral(" id=\"Sidebar3\"");

WriteLiteral(">\r\n                    <h4>Tech Blogs</h4>\r\n                    <ol");

WriteLiteral(" class=\"list-unstyled\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 63 "..\..\Views\Shared\_Layout.cshtml"
                   Write(Html.TechArchive(1));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </ol>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"sidebar-module sidebar-module-inset\"");

WriteLiteral(" id=\"Sidebar4\"");

WriteLiteral(">\r\n                    <h4>Music Blogs</h4>\r\n                    <ol");

WriteLiteral(" class=\"list-unstyled\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 70 "..\..\Views\Shared\_Layout.cshtml"
                   Write(Html.TechArchive(2));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </ol>\r\n                </div>\r\n\r\n\r\n            </div><!-- /" +
".blog-sidebar -->\r\n        </div>\r\n    </div><!-- /.container -->\r\n\r\n    <footer" +
"");

WriteLiteral(" class=\"blog-footer\"");

WriteLiteral(">\r\n        <p>Hey you\'ve read this far! You\'re officially cool! Send me an email " +
"to claim your prize!</p>\r\n        <p>\r\n        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Back to top</a>\r\n        </p>\r\n    </footer>\r\n\r\n<script");

WriteLiteral(" src=\"//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.4.0/languages/powershell.mi" +
"n.js\"");

WriteLiteral("></script>\r\n");

WriteLiteral("     ");

            
            #line 88 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/jscript"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    </body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
