#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CustomExtensions;
    using LachlanBarclayNet.Areas.Admin.ViewModels;
    using LachlanBarclayNet.DAO;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Account/QrCode.cshtml")]
    public partial class _Areas_Admin_Views_Account_QrCode_cshtml : System.Web.Mvc.WebViewPage<AdminQrCode>
    {
        public _Areas_Admin_Views_Account_QrCode_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\Admin\Views\Account\QrCode.cshtml"
  
    ViewBag.Title = "QR Code";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<br /><br />\r\n<div");

WriteLiteral(" id=\"qrcode\"");

WriteLiteral(" style=\"width: 200px\"");

WriteLiteral("></div>\r\n<br /><br />\r\n\r\n");

            
            #line 11 "..\..\Areas\Admin\Views\Account\QrCode.cshtml"
 using (Html.BeginForm(
           "QrCode",
           "Account",
           FormMethod.Post,
           new { @class = "form-horizontal", role = "form" }))
{
    
            
            #line default
            #line hidden
            
            #line 17 "..\..\Areas\Admin\Views\Account\QrCode.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 17 "..\..\Areas\Admin\Views\Account\QrCode.cshtml"
                            
    
            
            #line default
            #line hidden
            
            #line 18 "..\..\Areas\Admin\Views\Account\QrCode.cshtml"
Write(Html.ValidationSummary(false));

            
            #line default
            #line hidden
            
            #line 18 "..\..\Areas\Admin\Views\Account\QrCode.cshtml"
                                  
    
            
            #line default
            #line hidden
            
            #line 19 "..\..\Areas\Admin\Views\Account\QrCode.cshtml"
Write(Html.HiddenFor(m => m.SecretKey));

            
            #line default
            #line hidden
            
            #line 19 "..\..\Areas\Admin\Views\Account\QrCode.cshtml"
                                     
    
            
            #line default
            #line hidden
            
            #line 20 "..\..\Areas\Admin\Views\Account\QrCode.cshtml"
Write(Html.HiddenFor(m => m.BarcodeUrl));

            
            #line default
            #line hidden
            
            #line 20 "..\..\Areas\Admin\Views\Account\QrCode.cshtml"
                                      

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 22 "..\..\Areas\Admin\Views\Account\QrCode.cshtml"
   Write(Html.LabelFor(m => m.Code, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 24 "..\..\Areas\Admin\Views\Account\QrCode.cshtml"
       Write(Html.TextBoxFor(m => m.Code, new { @class = "form-control", autocomplete = "off" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n");

WriteLiteral("    <br />\r\n");

WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-offset-2 col-md-10\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" value=\"Enable\"");

WriteLiteral(" />\r\n        </div>\r\n    </div>\r\n");

WriteLiteral("    <br />\r\n");

            
            #line 34 "..\..\Areas\Admin\Views\Account\QrCode.cshtml"
    if (Model.Result.HasValue)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div>Result: ");

            
            #line 36 "..\..\Areas\Admin\Views\Account\QrCode.cshtml"
                Write(Model.Result);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 37 "..\..\Areas\Admin\Views\Account\QrCode.cshtml"
    }
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 1026), Tuple.Create("\"", 1061)
, Tuple.Create(Tuple.Create("", 1032), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery-3.4.1.min.js")
, 1032), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 1081), Tuple.Create("\"", 1106)
, Tuple.Create(Tuple.Create("", 1087), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/qrcode.js")
, 1087), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 1126), Tuple.Create("\"", 1158)
, Tuple.Create(Tuple.Create("", 1132), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.qrcode.js")
, 1132), false)
);

WriteLiteral("></script>\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n\r\n        var barcodeUrl = \"");

            
            #line 46 "..\..\Areas\Admin\Views\Account\QrCode.cshtml"
                     Write(Html.Raw(Model.BarcodeUrl));

            
            #line default
            #line hidden
WriteLiteral(@""";

        $(function () {
            $(""#qrcode"").qrcode({
                text: barcodeUrl,
                width: 200,
                height: 200,
                colorDark: ""#000000"",
                colorLight: ""#ffffff""
            });
            $(""#Code"").focus();
        });

</script>");

        }
    }
}
#pragma warning restore 1591
