#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CustomExtensions;
    using LachlanBarclayNet.Areas.Admin.ViewModels;
    using LachlanBarclayNet.DAO;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Login/Index.cshtml")]
    public partial class _Areas_Admin_Views_Login_Index_cshtml : System.Web.Mvc.WebViewPage<LoginIndexViewModel>
    {
        public _Areas_Admin_Views_Login_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\Admin\Views\Login\Index.cshtml"
  
    ViewBag.Title = "Login";
    Layout = "";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>Login</h2>\r\n\r\n");

            
            #line 10 "..\..\Areas\Admin\Views\Login\Index.cshtml"
 using (Html.BeginForm())
{
    
            
            #line default
            #line hidden
            
            #line 12 "..\..\Areas\Admin\Views\Login\Index.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 12 "..\..\Areas\Admin\Views\Login\Index.cshtml"
                            

    
            
            #line default
            #line hidden
            
            #line 14 "..\..\Areas\Admin\Views\Login\Index.cshtml"
Write(Html.TextBoxFor(x => x.username));

            
            #line default
            #line hidden
WriteLiteral("<br />\r\n");

            
            #line 15 "..\..\Areas\Admin\Views\Login\Index.cshtml"
    
            
            #line default
            #line hidden
            
            #line 15 "..\..\Areas\Admin\Views\Login\Index.cshtml"
Write(Html.PasswordFor(x => x.password));

            
            #line default
            #line hidden
WriteLiteral("<br />\r\n");

            
            #line 16 "..\..\Areas\Admin\Views\Login\Index.cshtml"
    
            
            #line default
            #line hidden
            
            #line 16 "..\..\Areas\Admin\Views\Login\Index.cshtml"
Write(Html.TextBoxFor(x => x.qrcode));

            
            #line default
            #line hidden
            
            #line 16 "..\..\Areas\Admin\Views\Login\Index.cshtml"
                                   

            
            #line default
            #line hidden
WriteLiteral("    <br />");

WriteLiteral("<br />\r\n");

WriteLiteral("    <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Submit\"");

WriteLiteral(" />\r\n");

            
            #line 19 "..\..\Areas\Admin\Views\Login\Index.cshtml"

}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 22 "..\..\Areas\Admin\Views\Login\Index.cshtml"
 if (Model != null)
{

            
            #line default
            #line hidden
WriteLiteral("    <br />");

WriteLiteral("<br />\r\n");

            
            #line 25 "..\..\Areas\Admin\Views\Login\Index.cshtml"
    if (Model.FailCount.HasValue)
    {

            
            #line default
            #line hidden
WriteLiteral("        <p>Fail count: ");

            
            #line 27 "..\..\Areas\Admin\Views\Login\Index.cshtml"
                  Write(Model.FailCount.Value);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 28 "..\..\Areas\Admin\Views\Login\Index.cshtml"
    }

    if (Model.LockedOut.HasValue)
    {

            
            #line default
            #line hidden
WriteLiteral("        <p>Locked out since: ");

            
            #line 32 "..\..\Areas\Admin\Views\Login\Index.cshtml"
                        Write(Model.LockedOut.Value);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 33 "..\..\Areas\Admin\Views\Login\Index.cshtml"
    }
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
