#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CustomExtensions;
    using LachlanBarclayNet.DAO;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Index.cshtml")]
    public partial class _Views_Home_Index_cshtml : System.Web.Mvc.WebViewPage<LachlanBarclayNet.ViewModel.IndexBlogViewModel>
    {
        public _Views_Home_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Home\Index.cshtml"
  
    if (Model.Category == null)
    {
        ViewBag.MenuItemClass1 = "active";
        ViewBag.Title = "Lachlan (Rocklan) Barclay's Blog";
        ViewBag.Description = "Lachlan's blog, covering programming, guitars and more programming and more guitars.";
    }
    if (Model.Category == "technical")
    {
        ViewBag.MenuItemClass2 = "active";
        ViewBag.Title = "Lachlan (Rocklan) Barclay's Tech Blog";
        ViewBag.Description = "Lachlan's tech blog, covering programming, programming and more programming.";
    }
    if (Model.Category == "music")
    {
        ViewBag.MenuItemClass3 = "active";
        ViewBag.Description = "Lachlan's music blog, covering guitars, music, guitars and more guitars.";
    }
    if (ViewBag.Title == "Contact Me")
    {
        ViewBag.MenuItemClass4 = "active";
        ViewBag.Description = "Contact Lachlan (Rocklan) Barclay";
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n");

            
            #line 29 "..\..\Views\Home\Index.cshtml"
 foreach (Post post in Model.Posts)
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"blog-post\"");

WriteLiteral(">\r\n        <h2");

WriteLiteral(" class=\"blog-post-title\"");

WriteLiteral(">\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1102), Tuple.Create("\"", 1179)
, Tuple.Create(Tuple.Create("", 1109), Tuple.Create("/", 1109), true)
            
            #line 33 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1110), Tuple.Create<System.Object, System.Int32>(post.PostDate.Year
            
            #line default
            #line hidden
, 1110), false)
, Tuple.Create(Tuple.Create("", 1129), Tuple.Create("/", 1129), true)
            
            #line 33 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1130), Tuple.Create<System.Object, System.Int32>(post.PostDate.Month.ToString("00")
            
            #line default
            #line hidden
, 1130), false)
, Tuple.Create(Tuple.Create("", 1165), Tuple.Create("/", 1165), true)
            
            #line 33 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1166), Tuple.Create<System.Object, System.Int32>(post.PostUrl
            
            #line default
            #line hidden
, 1166), false)
);

WriteLiteral(">");

            
            #line 33 "..\..\Views\Home\Index.cshtml"
                                                                                        Write(post.PostTitle);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n        </h2>\r\n        <p");

WriteLiteral(" class=\"blog-post-meta\"");

WriteLiteral(">");

            
            #line 35 "..\..\Views\Home\Index.cshtml"
                             Write(post.PostDate.ToNiceDate());

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 36 "..\..\Views\Home\Index.cshtml"
        
            
            #line default
            #line hidden
            
            #line 36 "..\..\Views\Home\Index.cshtml"
         if (post.PostText.Length > 1500)
        {
            
            
            #line default
            #line hidden
            
            #line 38 "..\..\Views\Home\Index.cshtml"
       Write(Html.Raw(post.PostText.Substring(0, 1500)));

            
            #line default
            #line hidden
WriteLiteral("<span>...</span>\r\n");

            
            #line 39 "..\..\Views\Home\Index.cshtml"
        }
        else
        {
            
            
            #line default
            #line hidden
            
            #line 42 "..\..\Views\Home\Index.cshtml"
       Write(Html.Raw(post.PostText));

            
            #line default
            #line hidden
            
            #line 42 "..\..\Views\Home\Index.cshtml"
                                    
        }

            
            #line default
            #line hidden
WriteLiteral("        <br /><a");

WriteLiteral(" class=\"btn btn-primary\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1536), Tuple.Create("\"", 1613)
, Tuple.Create(Tuple.Create("", 1543), Tuple.Create("/", 1543), true)
            
            #line 44 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1544), Tuple.Create<System.Object, System.Int32>(post.PostDate.Year
            
            #line default
            #line hidden
, 1544), false)
, Tuple.Create(Tuple.Create("", 1563), Tuple.Create("/", 1563), true)
            
            #line 44 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1564), Tuple.Create<System.Object, System.Int32>(post.PostDate.Month.ToString("00")
            
            #line default
            #line hidden
, 1564), false)
, Tuple.Create(Tuple.Create("", 1599), Tuple.Create("/", 1599), true)
            
            #line 44 "..\..\Views\Home\Index.cshtml"
                        , Tuple.Create(Tuple.Create("", 1600), Tuple.Create<System.Object, System.Int32>(post.PostUrl
            
            #line default
            #line hidden
, 1600), false)
);

WriteLiteral(">Read More -></a>\r\n\r\n    </div>\r\n");

            
            #line 47 "..\..\Views\Home\Index.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 49 "..\..\Views\Home\Index.cshtml"
 if (Model.NextButtonSearchParams != null)
{

            
            #line default
            #line hidden
WriteLiteral("    <nav>\r\n        <ul");

WriteLiteral(" class=\"pager\"");

WriteLiteral(">\r\n            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1756), Tuple.Create("\"", 1801)
, Tuple.Create(Tuple.Create("", 1763), Tuple.Create<System.Object, System.Int32>(Href("~/search?")
, 1763), false)
            
            #line 53 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1772), Tuple.Create<System.Object, System.Int32>(Model.NextButtonSearchParams
            
            #line default
            #line hidden
, 1772), false)
);

WriteLiteral(">Next</a></li>\r\n        </ul>\r\n    </nav>\r\n");

            
            #line 56 "..\..\Views\Home\Index.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 59 "..\..\Views\Home\Index.cshtml"
 if (!string.Equals((string)System.Configuration.ConfigurationManager.AppSettings["environment"], "dev"))
{

            
            #line default
            #line hidden
WriteLiteral(@"    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
                m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-2382034-1', 'auto');
        ga('send', 'pageview');

    </script>
");

            
            #line 73 "..\..\Views\Home\Index.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
