#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CustomExtensions;
    using LachlanBarclayNet.DAO;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Index.cshtml")]
    public partial class _Views_Home_Index_cshtml : System.Web.Mvc.WebViewPage<LachlanBarclayNet.ViewModel.IndexBlogViewModel>
    {
        public _Views_Home_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Home\Index.cshtml"
  
    if (Model.Category == null)
    {
        ViewBag.MenuItemClass1 = "active";
        ViewBag.Title = "Lachlan (Rocklan) Barclay's Blog";
        ViewBag.Description = "Lachlan's blog, covering programming, guitars and more programming and more guitars.";
    }
    if (Model.Category == "technical")
    {
        ViewBag.MenuItemClass2 = "active";
        ViewBag.Title = "Lachlan (Rocklan) Barclay's Tech Blog";
        ViewBag.Description = "Lachlan's tech blog, covering programming, programming and more programming.";
    }
    if (Model.Category == "music")
    {
        ViewBag.MenuItemClass3 = "active";
        ViewBag.Description = "Lachlan's music blog, covering guitars, music, guitars and more guitars.";
    }
    if (ViewBag.Title == "Contact Me")
    {
        ViewBag.MenuItemClass4 = "active";
        ViewBag.Description = "Contact Lachlan (Rocklan) Barclay";
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 28 "..\..\Views\Home\Index.cshtml"
 foreach (LachlanBarclayNet.DAO.Standard.Post post in Model.Posts)
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"blog-post\"");

WriteLiteral(">\r\n        <h2");

WriteLiteral(" class=\"blog-post-title\"");

WriteLiteral(">\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1131), Tuple.Create("\"", 1209)
, Tuple.Create(Tuple.Create("", 1138), Tuple.Create<System.Object, System.Int32>(Href("~/")
, 1138), false)
            
            #line 32 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1140), Tuple.Create<System.Object, System.Int32>(post.PostDate.Year
            
            #line default
            #line hidden
, 1140), false)
, Tuple.Create(Tuple.Create("", 1159), Tuple.Create("/", 1159), true)
            
            #line 32 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1160), Tuple.Create<System.Object, System.Int32>(post.PostDate.Month.ToString("00")
            
            #line default
            #line hidden
, 1160), false)
, Tuple.Create(Tuple.Create("", 1195), Tuple.Create("/", 1195), true)
            
            #line 32 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1196), Tuple.Create<System.Object, System.Int32>(post.PostUrl
            
            #line default
            #line hidden
, 1196), false)
);

WriteLiteral(">");

            
            #line 32 "..\..\Views\Home\Index.cshtml"
                                                                                         Write(post.PostTitle);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n        </h2>\r\n        <p");

WriteLiteral(" class=\"blog-post-meta\"");

WriteLiteral(">");

            
            #line 34 "..\..\Views\Home\Index.cshtml"
                             Write(post.PostDate.ToNiceDate());

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 35 "..\..\Views\Home\Index.cshtml"
        
            
            #line default
            #line hidden
            
            #line 35 "..\..\Views\Home\Index.cshtml"
         if (post.PostText.Length > 1500)
        {
            
            
            #line default
            #line hidden
            
            #line 37 "..\..\Views\Home\Index.cshtml"
       Write(Html.Raw(post.PostText.Substring(0, 1500)));

            
            #line default
            #line hidden
WriteLiteral("<span>...</span>\r\n");

            
            #line 38 "..\..\Views\Home\Index.cshtml"
        }
        else
        {
            
            
            #line default
            #line hidden
            
            #line 41 "..\..\Views\Home\Index.cshtml"
       Write(Html.Raw(post.PostText));

            
            #line default
            #line hidden
            
            #line 41 "..\..\Views\Home\Index.cshtml"
                                    
        }

            
            #line default
            #line hidden
WriteLiteral("        <br /><a");

WriteLiteral(" class=\"btn btn-primary\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1566), Tuple.Create("\"", 1644)
, Tuple.Create(Tuple.Create("", 1573), Tuple.Create<System.Object, System.Int32>(Href("~/")
, 1573), false)
            
            #line 43 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1575), Tuple.Create<System.Object, System.Int32>(post.PostDate.Year
            
            #line default
            #line hidden
, 1575), false)
, Tuple.Create(Tuple.Create("", 1594), Tuple.Create("/", 1594), true)
            
            #line 43 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1595), Tuple.Create<System.Object, System.Int32>(post.PostDate.Month.ToString("00")
            
            #line default
            #line hidden
, 1595), false)
, Tuple.Create(Tuple.Create("", 1630), Tuple.Create("/", 1630), true)
            
            #line 43 "..\..\Views\Home\Index.cshtml"
                         , Tuple.Create(Tuple.Create("", 1631), Tuple.Create<System.Object, System.Int32>(post.PostUrl
            
            #line default
            #line hidden
, 1631), false)
);

WriteLiteral(">Read More -></a>\r\n\r\n    </div>\r\n");

            
            #line 46 "..\..\Views\Home\Index.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 48 "..\..\Views\Home\Index.cshtml"
 if (Model.NextButtonSearchParams != null)
{

            
            #line default
            #line hidden
WriteLiteral("    <nav>\r\n        <ul");

WriteLiteral(" class=\"pager\"");

WriteLiteral(">\r\n            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1787), Tuple.Create("\"", 1832)
, Tuple.Create(Tuple.Create("", 1794), Tuple.Create<System.Object, System.Int32>(Href("~/search?")
, 1794), false)
            
            #line 52 "..\..\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1803), Tuple.Create<System.Object, System.Int32>(Model.NextButtonSearchParams
            
            #line default
            #line hidden
, 1803), false)
);

WriteLiteral(">Next</a></li>\r\n        </ul>\r\n    </nav>\r\n");

            
            #line 55 "..\..\Views\Home\Index.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
