#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CustomExtensions;
    using LachlanBarclayNet.DAO;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Sitemap/Index.cshtml")]
    public partial class _Views_Sitemap_Index_cshtml : System.Web.Mvc.WebViewPage<LachlanBarclayNet.ViewModel.SitemapIndexViewModel>
    {
        public _Views_Sitemap_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Sitemap\Index.cshtml"
  
    Layout = "";

            
            #line default
            #line hidden
WriteLiteral("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n<urlset");

WriteLiteral(" xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\"");

WriteLiteral(">\r\n");

            
            #line 6 "..\..\Views\Sitemap\Index.cshtml"
    
            
            #line default
            #line hidden
            
            #line 6 "..\..\Views\Sitemap\Index.cshtml"
     foreach (var url in Model.Urls)
    {

            
            #line default
            #line hidden
WriteLiteral("        <url>\r\n            <loc>");

            
            #line 9 "..\..\Views\Sitemap\Index.cshtml"
            Write(url.Url);

            
            #line default
            #line hidden
WriteLiteral("</loc>\r\n        </url>\r\n");

            
            #line 11 "..\..\Views\Sitemap\Index.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</urlset>\r\n");

        }
    }
}
#pragma warning restore 1591
