#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CustomExtensions;
    using LachlanBarclayNet.Areas.Admin.ViewModels;
    using LachlanBarclayNet.DAO;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Post/Edit.cshtml")]
    public partial class _Areas_Admin_Views_Post_Edit_cshtml : System.Web.Mvc.WebViewPage<LachlanBarclayNet.DAO.Post>
    {
        public _Areas_Admin_Views_Post_Edit_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\Admin\Views\Post\Edit.cshtml"
  
                /**/

                ViewBag.Title = "Edit";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\n    .editor-field {\r\n        margin-bottom: 1em;\r\n    }\r\n\r\n    .editor-label {" +
"\r\n        margin-bottom: 5px;\r\n    }\r\n</style>\r\n\r\n\r\n<h2>Edit</h2>\r\n\r\n");

            
            #line 22 "..\..\Areas\Admin\Views\Post\Edit.cshtml"
 if (ViewBag.action != null)
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" style=\"background: green; color: white; padding: 10px;\"");

WriteLiteral(">");

            
            #line 24 "..\..\Areas\Admin\Views\Post\Edit.cshtml"
                                                            Write(ViewBag.action);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("    <br />\r\n");

            
            #line 26 "..\..\Areas\Admin\Views\Post\Edit.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 28 "..\..\Areas\Admin\Views\Post\Edit.cshtml"
 using (Html.BeginForm())
{
    
            
            #line default
            #line hidden
            
            #line 30 "..\..\Areas\Admin\Views\Post\Edit.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 30 "..\..\Areas\Admin\Views\Post\Edit.cshtml"
                            
    
            
            #line default
            #line hidden
            
            #line 31 "..\..\Areas\Admin\Views\Post\Edit.cshtml"
Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
            
            #line 31 "..\..\Areas\Admin\Views\Post\Edit.cshtml"
                                 


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"editor-label\"");

WriteLiteral(">\r\n        Post go live date\r\n    </div>\r\n");

WriteLiteral("    <div");

WriteLiteral(" class=\"editor-field\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 37 "..\..\Areas\Admin\Views\Post\Edit.cshtml"
   Write(Html.EditorFor(model => model.PostDate));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 38 "..\..\Areas\Admin\Views\Post\Edit.cshtml"
   Write(Html.ValidationMessageFor(model => model.PostDate));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

            
            #line 40 "..\..\Areas\Admin\Views\Post\Edit.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"editor-label\"");

WriteLiteral(">\r\n        Post Type\r\n    </div>\r\n");

WriteLiteral("    <div");

WriteLiteral(" class=\"editor-field\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 45 "..\..\Areas\Admin\Views\Post\Edit.cshtml"
   Write(Html.DropDownList("PostTypeID", String.Empty));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 46 "..\..\Areas\Admin\Views\Post\Edit.cshtml"
   Write(Html.ValidationMessageFor(model => model.PostTypeID));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

            
            #line 48 "..\..\Areas\Admin\Views\Post\Edit.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"editor-label\"");

WriteLiteral(">\r\n        Title\r\n    </div>\r\n");

WriteLiteral("    <div");

WriteLiteral(" class=\"editor-field\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 53 "..\..\Areas\Admin\Views\Post\Edit.cshtml"
   Write(Html.TextBoxFor(model => model.PostTitle, new { style = "width: 100%", maxlength = "255" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 54 "..\..\Areas\Admin\Views\Post\Edit.cshtml"
   Write(Html.ValidationMessageFor(model => model.PostTitle));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

            
            #line 56 "..\..\Areas\Admin\Views\Post\Edit.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"editor-label\"");

WriteLiteral(">\r\n        Description (for RSS)\r\n    </div>\r\n");

WriteLiteral("    <div");

WriteLiteral(" class=\"editor-field\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 61 "..\..\Areas\Admin\Views\Post\Edit.cshtml"
   Write(Html.TextBoxFor(model => model.PostDescription, new { style = "width: 100%", maxlength = "255" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 62 "..\..\Areas\Admin\Views\Post\Edit.cshtml"
   Write(Html.ValidationMessageFor(model => model.PostDescription));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

            
            #line 64 "..\..\Areas\Admin\Views\Post\Edit.cshtml"

    
            
            #line default
            #line hidden
            
            #line 65 "..\..\Areas\Admin\Views\Post\Edit.cshtml"
Write(Html.HiddenFor(model => model.PostID));

            
            #line default
            #line hidden
            
            #line 65 "..\..\Areas\Admin\Views\Post\Edit.cshtml"
                                          


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"editor-label\"");

WriteLiteral(">\r\n        Friendly URL\r\n    </div>\r\n");

WriteLiteral("    <div");

WriteLiteral(" class=\"editor-field\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 71 "..\..\Areas\Admin\Views\Post\Edit.cshtml"
   Write(Html.EditorFor(model => model.PostUrl));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 72 "..\..\Areas\Admin\Views\Post\Edit.cshtml"
   Write(Html.ValidationMessageFor(model => model.PostUrl));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

            
            #line 74 "..\..\Areas\Admin\Views\Post\Edit.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"editor-label\"");

WriteLiteral(">\r\n        Published\r\n    </div>\r\n");

WriteLiteral("    <div");

WriteLiteral(" class=\"editor-field\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 79 "..\..\Areas\Admin\Views\Post\Edit.cshtml"
   Write(Html.EditorFor(model => model.Published));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 80 "..\..\Areas\Admin\Views\Post\Edit.cshtml"
   Write(Html.ValidationMessageFor(model => model.Published));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

            
            #line 82 "..\..\Areas\Admin\Views\Post\Edit.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" style=\"width: 49%; float: left;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"editor-label\"");

WriteLiteral(">\r\n            Content\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"editor-field\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 88 "..\..\Areas\Admin\Views\Post\Edit.cshtml"
       Write(Html.TextAreaFor(model => model.PostText, new { style = "width:100%; height: 600px" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 89 "..\..\Areas\Admin\Views\Post\Edit.cshtml"
       Write(Html.ValidationMessageFor(model => model.PostText));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n");

WriteLiteral("    <div");

WriteLiteral(" style=\"width: 49%; float: right\"");

WriteLiteral(" id=\"RealtimePreviewDiv\"");

WriteLiteral(">\r\n\r\n    </div>\r\n");

WriteLiteral("    <br");

WriteLiteral(" style=\"clear: both\"");

WriteLiteral(" />\r\n");

WriteLiteral("    <p>\r\n        <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Save\"");

WriteLiteral(" />\r\n    </p>\r\n");

            
            #line 99 "..\..\Areas\Admin\Views\Post\Edit.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<br");

WriteLiteral(" style=\"clear: both\"");

WriteLiteral(" />\r\n<div>\r\n");

WriteLiteral("    ");

            
            #line 104 "..\..\Areas\Admin\Views\Post\Edit.cshtml"
Write(Html.ActionLink("Back to List", "Index"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n\r\n");

            
            #line 108 "..\..\Areas\Admin\Views\Post\Edit.cshtml"
Write(Scripts.Render("~/bundles/jscript"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    function renderPreview() {
        var content = $(""#PostText"").val();

        var title = $(""#PostTitle"").val();
        var publishdate = $(""#PostDate"").val();
        var preview = ""<h2 style='margin-bottom: 0px'>"" + title + ""</h2>"";
        preview += ""<div style='color: gray; margin-bottom:1em'>"" + publishdate + ""</div>"";
        preview += content;

        $(""#RealtimePreviewDiv"").html(preview);
    }

    $(document).ready(function () {
        $(""#PostText"").on(""keyup"", function () {
            renderPreview();
        });
        renderPreview();
    });

</script>

");

        }
    }
}
#pragma warning restore 1591
