#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CustomExtensions;
    using LachlanBarclayNet.Areas.Admin.ViewModels;
    using LachlanBarclayNet.DAO;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Post/Img.cshtml")]
    public partial class _Areas_Admin_Views_Post_Img_cshtml : System.Web.Mvc.WebViewPage<AdminImgViewModel>
    {
        public _Areas_Admin_Views_Post_Img_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\Admin\Views\Post\Img.cshtml"
  
    ViewBag.Title = "Index";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>Img links</h2>\r\n\r\n<table>\r\n    <tr>\r\n        <th>Image</th>\r\n        <th>" +
"Fixed</th>\r\n    </tr>\r\n");

            
            #line 14 "..\..\Areas\Admin\Views\Post\Img.cshtml"
    
            
            #line default
            #line hidden
            
            #line 14 "..\..\Areas\Admin\Views\Post\Img.cshtml"
     foreach (var post in Model.Posts)
    {

            
            #line default
            #line hidden
WriteLiteral("    <tr>\r\n        <td><a");

WriteAttribute("href", Tuple.Create(" href=\"", 238), Tuple.Create("\"", 274)
, Tuple.Create(Tuple.Create("", 245), Tuple.Create("/Admin/Post/Edit/", 245), true)
            
            #line 17 "..\..\Areas\Admin\Views\Post\Img.cshtml"
, Tuple.Create(Tuple.Create("", 262), Tuple.Create<System.Object, System.Int32>(post.PostID
            
            #line default
            #line hidden
, 262), false)
);

WriteLiteral(">");

            
            #line 17 "..\..\Areas\Admin\Views\Post\Img.cshtml"
                                               Write(post.PostTitle);

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n        <td>\r\n");

            
            #line 19 "..\..\Areas\Admin\Views\Post\Img.cshtml"
            
            
            #line default
            #line hidden
            
            #line 19 "..\..\Areas\Admin\Views\Post\Img.cshtml"
             foreach (var img in post.images)
            {

            
            #line default
            #line hidden
WriteLiteral("            <div>\r\n");

WriteLiteral("                ");

            
            #line 22 "..\..\Areas\Admin\Views\Post\Img.cshtml"
           Write(img.Img);

            
            #line default
            #line hidden
WriteLiteral(" <br />\r\n            </div>\r\n");

            
            #line 24 "..\..\Areas\Admin\Views\Post\Img.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n    </tr>\r\n");

            
            #line 28 "..\..\Areas\Admin\Views\Post\Img.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</table>");

        }
    }
}
#pragma warning restore 1591
