#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CustomExtensions;
    using LachlanBarclayNet.Areas.Admin.ViewModels;
    using LachlanBarclayNet.DAO;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Post/Search.cshtml")]
    public partial class _Areas_Admin_Views_Post_Search_cshtml : System.Web.Mvc.WebViewPage<AdminSearchViewModel>
    {
        public _Areas_Admin_Views_Post_Search_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\Admin\Views\Post\Search.cshtml"
  
    ViewBag.Title = "Search";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>Post Search</h2>\r\n\r\n");

            
            #line 9 "..\..\Areas\Admin\Views\Post\Search.cshtml"
 using (Html.BeginForm())
{

            
            #line default
            #line hidden
WriteLiteral("    <div>\r\n");

WriteLiteral("        ");

            
            #line 12 "..\..\Areas\Admin\Views\Post\Search.cshtml"
   Write(Html.TextBoxFor(x => x.SearchString));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" />\r\n    </div>\r\n");

WriteLiteral("    <br />");

WriteLiteral("<br />\r\n");

            
            #line 16 "..\..\Areas\Admin\Views\Post\Search.cshtml"
    

            
            #line default
            #line hidden
WriteLiteral("    <table");

WriteLiteral(" style=\"width: 100%\"");

WriteLiteral(">\r\n        <tr>\r\n            <th");

WriteLiteral(" width=\"200px\"");

WriteLiteral(">\r\n                Display Date\r\n            </th>\r\n            <th");

WriteLiteral(" width=\"100px\"");

WriteLiteral(">\r\n                Post Type\r\n            </th>\r\n            <th>\r\n              " +
"  Post\r\n            </th>\r\n            <th");

WriteLiteral(" width=\"150px\"");

WriteLiteral("></th>\r\n        </tr>\r\n\r\n");

            
            #line 31 "..\..\Areas\Admin\Views\Post\Search.cshtml"
        
            
            #line default
            #line hidden
            
            #line 31 "..\..\Areas\Admin\Views\Post\Search.cshtml"
         foreach (var item in Model.Posts)
        {

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n                <td>\r\n");

WriteLiteral("                    ");

            
            #line 35 "..\..\Areas\Admin\Views\Post\Search.cshtml"
               Write(Html.DisplayFor(modelItem => item.PostDate));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n                <td>\r\n");

WriteLiteral("                    ");

            
            #line 38 "..\..\Areas\Admin\Views\Post\Search.cshtml"
               Write(Html.DisplayFor(modelItem => item.PostType.PostTypeName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n                <td>\r\n");

WriteLiteral("                    ");

            
            #line 41 "..\..\Areas\Admin\Views\Post\Search.cshtml"
               Write(Html.ActionLink(item.PostTitle, "Edit", new { id = item.PostID }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n                <td>\r\n");

WriteLiteral("                    ");

            
            #line 44 "..\..\Areas\Admin\Views\Post\Search.cshtml"
               Write(Html.ActionLink("Preview", "Details", new { id = item.PostID }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 45 "..\..\Areas\Admin\Views\Post\Search.cshtml"
               Write(Html.ActionLink("Delete", "Delete", new { id = item.PostID }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n            </tr>\r\n");

            
            #line 48 "..\..\Areas\Admin\Views\Post\Search.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </table>\r\n");

            
            #line 50 "..\..\Areas\Admin\Views\Post\Search.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
